changelog:
  categories:
    - title: Breaking changes
      labels:
        - breaking-change
        - semver-major
    - title: Features
      labels:
        - feature
        - enhancement
    - title: Fixes
      labels:
        - fix
        - bug
        - bugfix
    - title: Security
      labels:
        - security
    - title: Maintenance
      labels:
        - maintenance
        - refactor
        - docs
    - title: Dependencies and automation
      labels:
        - dependencies
        - github_actions
    - title: Other merged pull requests
      labels:
        - "*"
